name: Instances checks

on:
  push:
    branches:
      - main
    paths: ["src/**", .github/workflows/status.yml, .github/status_update.py, .github/check_solution_json.py]

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Dockerfile
        run: |
          cd ${GITHUB_WORKSPACE}/src
          docker build . -t cdmo


      - name: Generate results
        run: |
          docker run -v ${GITHUB_WORKSPACE}/results:/cdmo/results cdmo --verbose --timeout=300 --mem-limit=5120

      - name: Generate checks
        run: |
          cd ${GITHUB_WORKSPACE}/.github
          python3 check_solution_json.py ${GITHUB_WORKSPACE}/src/instances ${GITHUB_WORKSPACE}/results/ > /tmp/instances_checks.json

      - name: Update status in README
        run: |
          cd ${GITHUB_WORKSPACE}/.github
          python3 status_update.py \
            --checks-file=/tmp/instances_checks.json \
            --readme-file=${GITHUB_WORKSPACE}/README.md \
            --results-git-path=./results


      - name: Push status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${GITHUB_WORKSPACE}/README.md
          git add ${GITHUB_WORKSPACE}/results/*
          git commit -m "Update status" || true
          git push || true